# -*- coding: utf-8 -*-
"""31.03,26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yw3o8LQ5k7-0spq2mbwiNYikyHQ3JV7a
"""

nama = 'galang'
 usia = 20
 lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

usia = input('masukan usia anda: ')

print(type(usia))

panjang = input('masukan panjang: ')
lebar = input('masukan lebar: ')

luas = int(panjang) * int(lebar)

panjang = int(input('masukan panjang: '))
lebar = float(input('masukan lebar: '))

print('luas =',panjang * lebar)

nama = 'wudi'
tahun_lahir = 2000

print(nama + 'lahir di tahun'+ str(tahun_lahir))

kata = 'jeruk'