# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

format str pada phy
"""

template = 'halo,saya %s dari %s'

print(template %('danu galang','indonesia'))

"""fungsi format"""

template = 'halo,saya {nama} dari {asal}'
template_2  = 'saya suka makan {} dan minum {}'

print(template.format(nama='danu galang',asal='indonesia'))
print(template_2.format('nasi goreng','es teh'))

"""str interpolation"""

nama = "danu galang"
asal = "indonesia"

print(f'perkenalkan saya {nama} asal saya dari {asal}')

alamat = 'surabaya,jawa timur,indonesia'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

"""MEMECAH STRING

"""

print('!'.join(['kamu','gak','suka']))

print('halo siapa nama kamu'.upper())
print('halo siapa nama kamu'.lower())
print('halo siapa nama kamu'.title())
print('halo siapa nama kamu'.swapcase())

angka = ('67890')

print('index angka 8:',angka.find('8'))
print('index angka 89:',angka.find('89'))
print('index angka 33:',angka.find('33'))

asal = 'indonesia'

print(asal.find('o'))
print(asal.find('ne'))

"""mereplace kata string

"""

ibu_kota = 'Negara'

print(ibu_kota.replace('a','o'))
print(ibu_kota.replace('ra','ga'))
print(ibu_kota.replace('a',''))

"""hitung jumlah karakter"""

paragraf = 'gemparnya kabar perang dunia ke tiga'
x = paragraf.count("per")

print(f'kata "per" muncul sebanyak {x} kali')