# -*- coding: utf-8 -*-
"""escape character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-k_43efYoZQF3RVHSnjQyNDw34SseqOM
"""

print ('dia berkata :"pergilah!"')

print("aku menimpali:\"apakah kau ingin aku'angkkat kaki'?!\"" )

print("\\(^_^)/ (\\-_-/)")

