# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3sRitGm2KZOSzxaBpA1HugLp1wM9lrr
"""

nama="danu galang"
asal="indonesia"

print(nama)

print(asal)

print(nama+asal)

print("halo,nama saya",nama,"asal saya dari",asal)

data_lengkap=nama + asal



"""string non string"""

asal_kota = "bandar lampung"
kode_pos = 3155

asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)