# -*- coding: utf-8 -*-
"""UTS KELOMPOK COMPRO.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJ477Z0ruAbLAa1yhS9GBb4hDSLGKkdq

*   NAMA : DANU GALANNG SAPUTRA
*   NPM : 2451012016


*   MK : UTS KELOMPOK COMPRO
"""

# Data Mentah
raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"


# 1. Data Splitting (Double Split)
# Memisahkan string menjadi 2 tranksaksi berdasarkan tanda (;) menggunakan fungsi split
Transaksi = raw_log.split(";")
# Memisahkan setiap bagian data pada transaksi pertama berdasarkan tanda (#) menggunakan fungsi split
Transaksi_1 = Transaksi[0].split("#")
# Memisahkan setiap bagian data pada transaksi kedua berdasarkan tanda (#) menggunakan fungsi split
Transaksi_2 = Transaksi[1].split("#")


# 2. Advanced cleaning
# Menghapus label "ID:", "Nama", dll menggunakan replace(), lalu strip untuk menghapus spasi
# Transaksi 1
Transaksi_1[0] = Transaksi_1[0].replace("ID:", "").strip()
Transaksi_1[1] = Transaksi_1[1].replace("NAMA:", "").strip()
Transaksi_1[2] = Transaksi_1[2].replace("QTY:", "").strip()
Transaksi_1[3] = Transaksi_1[3].replace("PRICE:", "").strip()
# Transaksi 2
Transaksi_2[0] = Transaksi_2[0].replace("ID:", "").strip()
Transaksi_2[1] = Transaksi_2[1].replace("NAMA:", "").strip()
Transaksi_2[2] = Transaksi_2[2].replace("QTY:", "").strip()
Transaksi_2[3] = Transaksi_2[3].replace("PRICE:", "").strip()

# 3. Tranformasi & Casting
# Mengubah nama menu transaksi 1 & 2 menjadi title case
Menu_1 = Transaksi_1[1].title() #title() digunakan untuk membuat huruf awal jadi kapital
Menu_2 = Transaksi_2[1].title() #title() digunakan untuk membuat huruf awal jadi kapital
# Casting (mengubah tipe data string menjadi integer)
Qty1 = int(Transaksi_1[2])
Qty2 = int(Transaksi_2[2])
Price1 = int(Transaksi_1[3])
Price2 = int(Transaksi_2[3])

# 4. Perhitungan Aritmatika
subtotal_1 = Qty1 * Price1
subtotal_2 = Qty2 * Price2
total = subtotal_1 + subtotal_2


# 5. Output
print("="*55)
print("            LAPORAN HARIAN KEDAI SOU SPACE")
print("="*55)

print(f"{'Menu':<25}{'QTY':>5}{'Harga':>10}{'Subtotal':>12}")
print(f"{Menu_1:<25}{Qty1:>5}{Price1:>10}{subtotal_1:>12}")
print(f"{Menu_2:<25}{Qty2:>5}{Price2:>10}{subtotal_2:>12}")
print("="*55)
print(f"{'Total':<25}{'':>5}{'':>10}{total:>12}")
print("="*55)