# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!

operasi in pada string
"""

Berita='Ramai-ramai developer di seluruh dunia mulai menggunakan\
        teks editor masa kini seperti visual studio code,\
        atom,sublime text, dan lain sebagainya.'



print('sublime text'in Berita)
print('notepad++'in Berita)

"""memotong string"""

nama = 'Lendis Fabri'
print(nama[4])
print(nama[7])
print(nama[-1])
print(nama[-3])

"""slicing string"""

judul = 'Pelajaran matematika untuk SD'

print(judul[0:5])
print(judul[:10])
print(judul[10:15])
print(judul[-1:-3])
print(judul[:-3])
print(judul[-5:])

"""menghitung panjang string"""

print(len('indonesia'))
print(len('malaysia'))

"""memeriksa karakter awal string"""

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '6288776655443'
nomor_telepon_3 = '+628330033003'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

"""memeriksa karakter akhir string"""

email_1 = 'presiden@gmail.com'
email_2 = 'presiden@outlook.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gmail.com'))